### ISSUE TITLE
Module naming convention

### ISSUE THREAD

**Issue by bulli92** [multiply-org/multiply-core#1]
Avoid to have any '-' in the names of the modules and project names. This is not compliant with the python coding style conventions and results in import errors.

A statement `import multiply-dummy`does not work.

In the [PEP8 conventions](https://www.python.org/dev/peps/pep-0008/#naming-conventions) it says that
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

Thus recommendation would be to replace `multiply-dummy`with `multiply_dummy`

**Comment by TonioF** [comment]
The module has been renamed. If further violations of the PEP-8 should occur, we may open new issues - I don't think that renamings are worth raising issues, though.
